### PR TITLE
Added Bucketlist model

### LINKED ISSUE #19: Create a bucket list model
Is your feature request related to a problem? Please describe.
Currently, there is no bucket list model.

Describe the solution you'd like
Create a `./src/models/bucketlist.py` class and populate it with the bucket list model based on the [design](https://github.com/Rwothoromo/dreams/blob/master/src/designs/UML/UML%20Class%20Diagrams.png).

Describe alternatives you've considered
N/A

Additional context
N/A

### PR DESCRIPTION
**Pull request by asi7296**
#### What does this PR do?
Adds skeleton Bucketlist model as a class

#### Description of Task to be completed?
- 1. Implement skeletal Bucketlist model according to design

#### How should this be manually tested?
- Create an instance of the class, check for __init__ statements.

#### Any background context you want to provide?
Issue #19 

fixes #19

### CODE REVIEW

**Comment by Rwothoromo** [comment]
@asi7296 Could you adjust the init file; just like in the user model.

**Comment by asi7296** [comment]
@Rwothoromo  I've added the init file to export the user and bucketlist classes.

**Comment by asi7296** [comment]
@Rwothoromo The user model init has been updated.

**Comment by Rwothoromo** [comment]
@asi7296 Could you do the same for `bucketlist`?

**Comment by asi7296** [comment]
@Rwothoromo Yes, done.

**Comment by Rwothoromo** [comment]
@asi7296 Awesome.

**Pull request merged**
